// product data
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const OPEN_DETAIL = 'OPEN_DETAIL';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';
export const INIT_PRODUCTS = 'INIT_PRODUCTS';

// purchase product
export const PURCHASE_PRODUCT = 'PURCHASE_PRODUCT';
export const PURCHASE_PRODUCT_START = 'PURCHASE_PRODUCT_START';
export const PURCHASE_PRODUCT_SUCCESS = 'PURCHASE_PRODUCT_SUCCESS';
export const PURCHASE_PRODUCT_FAIL = 'PURCHASE_PRODUCT_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

 
// cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_WHOLE_ITEM = 'REMOVE_WHOLE_ITEM';
export const PURCHASE = 'PURCHASE';

// orders
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const ADD_ITEM = 'ADD_ITEM';
export const EDIT_OR_CONFIRM_ORDER_START = 'EDIT_OR_CONFIRM_ORDER_START';
export const EDIT_OR_CONFIRM_ORDERS = 'EDIT_OR_CONFIRM_ORDERS';
export const EDIT_OR_CONFIRM_ORDER_SUCCESS = 'EDIT_OR_CONFIRM_ORDER_SUCCESS';
export const EDIT_OR_CONFIRM_ORDER_FAIL = 'EDIT_OR_CONFIRM_ORDER_FAIL';

// users login
export const AUTH_USER = 'AUTH_USER';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// users signup
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

// admin
export const ADMIN_SUCCESS = 'ADMIN_SUCCESS';