export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const MESSAGE_SENT = 'MESSAGE_SENT';
export const SEND_MESSAGE_RESPONSE = 'SEND_MESSAGE_RESPONSE';
export const USER_CHANGED = 'USER_CHANGED';